package net.maxsoft.precioustracker.model.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import net.maxsoft.precioustracker.model.dao.PreciousMove;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table PRECIOUS_MOVE.
*/
public class PreciousMoveDao extends AbstractDao<PreciousMove, Long> {

    public static final String TABLENAME = "PRECIOUS_MOVE";

    /**
     * Properties of entity PreciousMove.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property FromWhere = new Property(1, String.class, "fromWhere", false, "FROM_WHERE");
        public final static Property ToWhere = new Property(2, String.class, "toWhere", false, "TO_WHERE");
        public final static Property DateMoved = new Property(3, java.util.Date.class, "dateMoved", false, "DATE_MOVED");
        public final static Property SnapshotFilePath = new Property(4, String.class, "snapshotFilePath", false, "SNAPSHOT_FILE_PATH");
        public final static Property Item = new Property(5, long.class, "item", false, "ITEM");
    };

    private DaoSession daoSession;

    private Query<PreciousMove> preciousItem_PreciousMoveListQuery;

    public PreciousMoveDao(DaoConfig config) {
        super(config);
    }
    
    public PreciousMoveDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'PRECIOUS_MOVE' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'FROM_WHERE' TEXT NOT NULL ," + // 1: fromWhere
                "'TO_WHERE' TEXT NOT NULL ," + // 2: toWhere
                "'DATE_MOVED' INTEGER NOT NULL ," + // 3: dateMoved
                "'SNAPSHOT_FILE_PATH' TEXT," + // 4: snapshotFilePath
                "'ITEM' INTEGER NOT NULL );"); // 5: item
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'PRECIOUS_MOVE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, PreciousMove entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getFromWhere());
        stmt.bindString(3, entity.getToWhere());
        stmt.bindLong(4, entity.getDateMoved().getTime());
 
        String snapshotFilePath = entity.getSnapshotFilePath();
        if (snapshotFilePath != null) {
            stmt.bindString(5, snapshotFilePath);
        }
        stmt.bindLong(6, entity.getItem());
    }

    @Override
    protected void attachEntity(PreciousMove entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public PreciousMove readEntity(Cursor cursor, int offset) {
        PreciousMove entity = new PreciousMove( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // fromWhere
            cursor.getString(offset + 2), // toWhere
            new java.util.Date(cursor.getLong(offset + 3)), // dateMoved
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // snapshotFilePath
            cursor.getLong(offset + 5) // item
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, PreciousMove entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFromWhere(cursor.getString(offset + 1));
        entity.setToWhere(cursor.getString(offset + 2));
        entity.setDateMoved(new java.util.Date(cursor.getLong(offset + 3)));
        entity.setSnapshotFilePath(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setItem(cursor.getLong(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(PreciousMove entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(PreciousMove entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "preciousMoveList" to-many relationship of PreciousItem. */
    public List<PreciousMove> _queryPreciousItem_PreciousMoveList(long item) {
        synchronized (this) {
            if (preciousItem_PreciousMoveListQuery == null) {
                QueryBuilder<PreciousMove> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Item.eq(null));
                preciousItem_PreciousMoveListQuery = queryBuilder.build();
            }
        }
        Query<PreciousMove> query = preciousItem_PreciousMoveListQuery.forCurrentThread();
        query.setParameter(0, item);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getPreciousItemDao().getAllColumns());
            builder.append(" FROM PRECIOUS_MOVE T");
            builder.append(" LEFT JOIN PRECIOUS_ITEM T0 ON T.'ITEM'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected PreciousMove loadCurrentDeep(Cursor cursor, boolean lock) {
        PreciousMove entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        PreciousItem preciousItem = loadCurrentOther(daoSession.getPreciousItemDao(), cursor, offset);
         if(preciousItem != null) {
            entity.setPreciousItem(preciousItem);
        }

        return entity;    
    }

    public PreciousMove loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<PreciousMove> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<PreciousMove> list = new ArrayList<PreciousMove>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<PreciousMove> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<PreciousMove> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
