package net.maxsoft.precioustracker.model.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import java.io.Serializable;
// KEEP INCLUDES END
/**
 * Entity mapped to table PRECIOUS_MOVE.
 */
public class PreciousMove implements Serializable {

    private Long id;
    /** Not-null value. */
    private String fromWhere;
    /** Not-null value. */
    private String toWhere;
    /** Not-null value. */
    private java.util.Date dateMoved;
    private String snapshotFilePath;
    private long itemId;

    // KEEP FIELDS - put your custom fields here
    private static final long serialVersionUID = 391145589830802800L;
    public static final String INTENT_MESSAGE = "intent.PreciousMove";
    // KEEP FIELDS END

    public PreciousMove() {
    }

    public PreciousMove(Long id) {
        this.id = id;
    }

    public PreciousMove(Long id, String fromWhere, String toWhere, java.util.Date dateMoved, String snapshotFilePath, long itemId) {
        this.id = id;
        this.fromWhere = fromWhere;
        this.toWhere = toWhere;
        this.dateMoved = dateMoved;
        this.snapshotFilePath = snapshotFilePath;
        this.itemId = itemId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getFromWhere() {
        return fromWhere;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFromWhere(String fromWhere) {
        this.fromWhere = fromWhere;
    }

    /** Not-null value. */
    public String getToWhere() {
        return toWhere;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setToWhere(String toWhere) {
        this.toWhere = toWhere;
    }

    /** Not-null value. */
    public java.util.Date getDateMoved() {
        return dateMoved;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDateMoved(java.util.Date dateMoved) {
        this.dateMoved = dateMoved;
    }

    public String getSnapshotFilePath() {
        return snapshotFilePath;
    }

    public void setSnapshotFilePath(String snapshotFilePath) {
        this.snapshotFilePath = snapshotFilePath;
    }

    public long getItemId() {
        return itemId;
    }

    public void setItemId(long itemId) {
        this.itemId = itemId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
