package net.maxsoft.precioustracker.model.dao;

import java.util.List;
import net.maxsoft.precioustracker.model.dao.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PRECIOUS_CATEGORY.
 */
public class PreciousCategory {

    private Long id;
    /** Not-null value. */
    private String cat_name;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient PreciousCategoryDao myDao;

    private List<PreciousItem> preciousItemList;

    public PreciousCategory() {
    }

    public PreciousCategory(Long id) {
        this.id = id;
    }

    public PreciousCategory(Long id, String cat_name) {
        this.id = id;
        this.cat_name = cat_name;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getPreciousCategoryDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getCat_name() {
        return cat_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCat_name(String cat_name) {
        this.cat_name = cat_name;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<PreciousItem> getPreciousItemList() {
        if (preciousItemList == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            PreciousItemDao targetDao = daoSession.getPreciousItemDao();
            List<PreciousItem> preciousItemListNew = targetDao._queryPreciousCategory_PreciousItemList(id);
            synchronized (this) {
                if(preciousItemList == null) {
                    preciousItemList = preciousItemListNew;
                }
            }
        }
        return preciousItemList;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetPreciousItemList() {
        preciousItemList = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
